FROM node:22.15.0-alpine AS build
WORKDIR /usr/src/app
COPY . .
COPY .env.production .env
RUN npm install && npm run build


FROM node:22.15.0-alpine

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist

RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]