version: "3"

services:
  react-app:
    image: react-app
    build: 
      context: ./client/
      dockerfile: Dockerfile.development
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - hackernews-app
    volumes:
      - ./client/:/usr/src/app
      - ./client/.env.development:/usr/src/app/.env
      - /usr/src/app/node_modules

  api-server:
    image: api-server
    build: 
      context: ./api-server/
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    networks:
      - hackernews-app
    volumes:
      - ./api-server/:/usr/src/app
       - ./api-server/.env.development:/usr/src/app/.env
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    networks:
      - hackernews-app
    volumes:
      - mongo-data:/data/db

networks:
  hackernews-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
