FROM node:22.15.0-alpine AS build
WORKDIR /usr/src/app
COPY . .
COPY .env.production .env
RUN npm install 
RUN npm run build




FROM node:22.15.0-alpine

WORKDIR /usr/src/app

COPY ./package.json ./
RUN npm install


COPY --from=build /usr/src/app/dist ./dist
COPY .env.production .env

EXPOSE 8080

CMD ["node", "dist/index.js"]
