FROM node:22.15.0-alpine AS build
WORKDIR /usr/src/app
COPY . .
COPY .env.production .env
RUN npm install && npm run build




FROM node:22.15.0-alpine

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .
COPY .env.production .env

EXPOSE 8080

CMD ["npm", "run", "serve"]